---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/rbac.yaml
  - manifests/policies.yaml
  - manifests/helm-controller.yaml
  - manifests/kustomize-controller.yaml
  - manifests/notification-controller.yaml
  - manifests/source-controller.yaml
images:
  - name: fluxcd/source-controller
    newName: ghcr.io/fluxcd/source-controller
  - name: fluxcd/kustomize-controller
    newName: ghcr.io/fluxcd/kustomize-controller
  - name: fluxcd/helm-controller
    newName: ghcr.io/fluxcd/helm-controller
  - name: fluxcd/notification-controller
    newName: ghcr.io/fluxcd/notification-controller
  - name: fluxcd/image-reflector-controller
    newName: ghcr.io/fluxcd/image-reflector-controller
  - name: fluxcd/image-automation-controller
    newName: ghcr.io/fluxcd/image-automation-controller
labels:
  - pairs:
      app.kubernetes.io/instance: flux-system
      app.kubernetes.io/part-of: flux
patches:
  # CIS hardening
  - target:
      kind: ServiceAccount
      labelSelector: app.kubernetes.io/part-of=flux
    patch: |
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: all
      automountServiceAccountToken: false
  - target:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=flux
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: whatever
      spec:
        template:
          metadata:
            annotations:
              # Required by Kubernetes node autoscaler
              cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
          spec:
            terminationGracePeriodSeconds: 60
            automountServiceAccountToken: true
            # Required by Pod Security Policy
            securityContext:
              runAsUser: 1000
              fsGroup: 1000
            containers:
              - name: manager
                # Required by Pod Security Policy
                securityContext:
                  runAsUser: 1000
                  runAsGroup: 1000
                  privileged: false
                  readOnlyRootFilesystem: true
                  allowPrivilegeEscalation: false
                  runAsNonRoot: true
                  capabilities:
                    drop:
                      - ALL
                  $patch: replace
  # Increase how many resources flux will reconcile at once
  - target:
      kind: Deployment
      name: helm-controller
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --concurrent=20
  - target:
      kind: Deployment
      name: kustomize-controller
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --concurrent=20
